version: '2.1'

volumes:
  db-data-17:

services:
  db-17:
    image: kartoza/postgis:17-3.5
    shm_size: 4gb
    volumes:
      - db-data-17:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: on-failure
    healthcheck:
      test: "exit 0"
